export const types = {

    UI_OPEN_MODAL:'UI_OPEN_MODAL',
    UI_CLOSE_MODAL: 'UI_CLOSE_MODAL',

    EVENT_SET_ACTIVE: 'EVENT_SET_ACTIVE',
    EVENT_ADD_NEW: 'EVENT_ADD_NEW',

    EVENT_CLEAR_ACTIVE_EVENT: 'EVENT_CLEAR_ACTIVE_EVENT',
    
    EVENT_UPDATED: 'EVENT_UPDATED',
    
}